### ISSUE TITLE
Rest Service Issue

### ISSUE THREAD

**Issue by Abhishek0510** [IBM/gdpr-fingerprint-pii#10]
Hi,

I am trying to use this application to conusme rest services ,but it gives me error "404"  -
 - [08/Mar/2018:16:28:18 +0530] "POST /PersonalDataScorer/forconsumer HTTP/1.1" 404 1054 .

Please let me know how to use this service.

Thanks,
Abhishek

**Comment by muralidharchavan** [comment]
Hi Abhishek.
Where have you deployed the application? Is it running? Are you able to hit the context-root of the deployed application?

**Comment by Abhishek0510** [comment]
I have deployed in Tomcat container and it's running and able to get the html Page using the URL -
localhost:8000/PersonalDataScorer/ - Where i am able to upload the Sample text but after that it's getting 404 error when it calls the rest service using Ajax call which is there in d3tree.js

**Comment by Abhishek0510** [comment]
Please let me know the solution.

Thanks,
Abhishek

**Comment by muralidharchavan** [comment]
Can you try to run it on Liberty please? From analyzing problem, looks like the jax-rs interfaces like ApplicationPath need to be used differently on servers other than Liberty.
