### ISSUE TITLE
Dead demo link

### ISSUE THREAD

**Issue by Clembl-git** [IBM/gdpr-fingerprint-pii#11]
Hello, 
I was very intrested to explore the demo capabilities before trying the tutoriel but the link in the description seems KO :
https://developer.ibm.com/patterns/fingerprinting-personal-data-from-unstructured-text/

**Comment by muralidharchavan** [comment]
Link in description opens EN documention. Anyway, documentation is available in both in EN and KO. EN - https://github.com/IBM/gdpr-fingerprint-pii 
KO - https://github.com/IBM/gdpr-fingerprint-pii/blob/master/README-ko.md

Hope this helps

**Comment by Clembl-git** [comment]
Sorry i meant that the link was broken but it's fixed now :)
