### ISSUE TITLE
IAM Apikey needs to be supported

### ISSUE THREAD

**Issue by jaumemir** [IBM/gdpr-fingerprint-pii#17]
IAM apikey credential needs support or, otherwise, application can not connect to NLU

Also update SDK version.

**Comment by muralidharchavan** [comment]
Hi. Code to use apikey is updated. However, when using updated SDK there are some errors and is taking time to resolve them for maven builds. However, as a workaround I had earlier created a branch called *ProcessChanges* which provides instructions with updated SDK but not using maven project. Also, in the master branch I have provided instructions to use *ProcessChanges* branch until we resolve issue with using updated SDK in maven projects.

**Comment by muralidharchavan** [comment]
Made necessary changes for Watson API updates.
